[package]
name = "glv-example-mean-field-replicator"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
publish = false

[dependencies]
general-lotka-volterra-rs = { path = "../.." }
scientific-workflow = "0.11.3"

[workspace]

[patch.crates-io]
ecological-model-core = { path = "../../../eco_core" }
